### ISSUE TITLE
Add drum kit?

### ISSUE THREAD

**Issue by iandaaci** [ryohey/signal#109]
This looks like a great tool - thank you for all your work.

**Is your feature request related to a problem? Please describe.**
I would love to be able to add a track for a drum kit (in addition to a keyboard).

**Describe the solution you'd like**
When creating a track, allow the option to choose between either a vertical keyboard or a drum kit. The drum kit could probably work in a similar way to the keyboard - it would just have a small number of channels / keys with one dedicated to each drum (kick, snare, clap, hi-hat, etc).

**Comment by ryohey** [comment]
That sounds great!
I would like to add the ability to freely set channels to tracks.
