### ISSUE TITLE
Note channel is missing when load and save a midi file

### ISSUE THREAD

**Issue by yuhengh** [ryohey/signal#141]
**Describe the bug**
Note channel is missing when load and save a midi file

**To Reproduce**
1. Open the attached midi file
2. Save to a new midi file
3. Channel information for all the notes is lost

**Expected behavior**
The channel information should be preserved.

Looks like channel is omitted in
https://github.com/ryohey/signal/blob/033dd5893555700f43e34a507b5279a742b3c726/src/common/helpers/noteAssembler.ts#L60
Any reason why?

[123.mid.zip](https://github.com/ryohey/signal/files/8005223/123.mid.zip)

**Comment by ryohey** [comment]
@yuhengh Currently, signal does not support midi files in Type0 format. If I were to implement it, the behavior would be to convert the file to Type 1 when opening it (split it into tracks for each channel). If I do that, the file will be converted to Type1 when it is saved, is that OK?

**Comment by yuhengh** [comment]
My use case is to correct wrong notes in a midi file during a performance. I would like to have as less change as the current midi file structure as possible since I want to load it back to the software (Hauptwerk) that records it. I'm not sure if the software is able to handle a type1 file correctly. Is it difficult to just preserve the midi channel to support both type0 and type1 file format?

**Comment by ryohey** [comment]
@yuhengh Hi, I've added support for the Type 0 format. Please give it a try.

**Comment by yuhengh** [comment]
It works, thanks!
