### ISSUE TITLE
Show notes also when it start before the current viewport in the piano roll

### ISSUE THREAD

**Issue by greenbech** [ryohey/signal#162]
**Is your feature request related to a problem? Please describe.**
I find it annoying that I can't see a note when it starts before the current viewport in the piano roll. Solving this would mostly just improve user experience, but there is a concrete bug when you thought you have scrolled to the beginning of a bar and add a note there, it will not appear in the piano roll. This can lead to duplicated notes it you click several times.

**Describe the solution you'd like**
I want to see notes even when they start before the current viewport in the piano roll.

**Describe alternatives you've considered**
It would be the current solution - but I think it is strictly better in every way to see the notes 

**Additional context**
I would like this to also apply to ghost notes

**Comment by ryohey** [comment]
I will fix this 👍
