### ISSUE TITLE
Load midi content on application start

### ISSUE THREAD

**Issue by iandaaci** [ryohey/signal#164]
**Is your feature request related to a problem? Please describe.**
It would be great if one was able to get the app to load custom midi content on startup.

**Describe the solution you'd like**
I think the perfect solution would be to provide a full programmable interface, but a quicker and simpler solution for the current setup (ie standalone app) might be something like:

* check for an optional CGI param that points to the location of a midi file,  eg https://signal.vercel.app/?midi=https://mysite.com/mymidifile.mid

(CORS would be an issue)

* send optional midi content through with a POST request

**Comment by ryohey** [comment]
I have implemented a function to open MIDI files from external websites in #293 
To work around the CORS issue, download the midi file in Cloud Functions and load it via Firestore.
You can open a MIDI file directly in signal by adding `open=<URL to midi file>` after the app URL.
Note that the MIDI file is cached on the signal server, so updates will not be reflected.
Please give it a try.
https://signal.vercel.app/edit?open=https://pianoscores.web.fc2.com/012_Home/Home.mid
