### ISSUE TITLE
MS edge crashes after closing with MIDI device plugged in.

### ISSUE THREAD

**Issue by Softy107** [ryohey/signal#193]
**Describe the bug**
When closing Signal with a MIDI keyboard plugged in, the entire browser crashes quickly.

**To Reproduce**
1. Go to Signal (on MS edge) with a MIDI device plugged in, and OmniMIDI installed as an output
2. Play a couple of notes with the MIDI device and unplug it
3. Close MS edge
4. See error / MS edge stops responding

**Expected behavior**
Signal closes and browser continues to run perfectly.

**Screenshots**
There is nothing to see other than MS edge not responding, and later closing by it self.

**Desktop (please complete the following information):**
 - OS: Windows 10 education
 - Browser : MS Edge 
 - Version : 103.0.1264.49 (Official build) (64-bit) (browser ver)

**Smartphone (please complete the following information):**
 ^ Couldn't plug in a MIDI device on my phone ^

**Additional context**
This also might not be a Signal issue, but a browser issue. I just wasn't sure so I wanted to report it here.
My MIDI device is an Alesis Concert Keyboard.

**Comment by ryohey** [comment]
Thank you for reporting!

**Comment by Softy107** [comment]
This issue was fixed during an unknown update, issue#193 was closed later on.
