### ISSUE TITLE
Windows/IOS desktop app w/ higher note support

### ISSUE THREAD

**Issue by Softy107** [ryohey/signal#194]
**Is your feature request related to a problem? Please describe.**
Although signal is a great app, I feel like the 4MB size limit is a little... limiting.(mainly because signal can save above 4.4MB[before crashing] but can only load under 4MB files)

**Describe the solution you'd like**
A signal desktop app similar/just the same as the online version, but with higher performance and note amount limitation.

**Describe alternatives you've considered**
A good alternative could be extending the file load limit to something like 10MB, but if the files is above example... 2MB a warning would pop up saying that the file is too big and may cause performance issues.

**Additional context**
![Screenshot (218)](https://user-images.githubusercontent.com/103595729/179029003-3e5ee4bf-49ba-4595-ad8a-5f86740f62c5.png)

**Comment by ryohey** [comment]
@Softy107 There should not be the file size limit you gave me, and it sounds like there may be a programming problem. I will investigate it.
Thank you for reporting it!

**Comment by ryohey** [comment]
@Softy107 Can you send me the MIDI file that caused the problem?

**Comment by Softy107** [comment]
I can't get on my PC now but when I will be able to, I will try it again and send you the file.
