### ISSUE TITLE
signal.vercel.com seems to be unavailable

### ISSUE THREAD

**Issue by maks** [ryohey/signal#198]
Thank you for such a wonderful web app. I briefly tried it earlier today but now when I tried again I currently get a 404 from https://signal.vercel.com/ :
![image](https://user-images.githubusercontent.com/71999/180600147-8aedde34-4362-4b33-bc49-acbf5401feeb.png)

**Comment by ryohey** [comment]
@maks Where that URL came from? Try https://signal.vercel.app/. not `.com`

**Comment by maks** [comment]
ah sorry @ryohey I don't know how I ended up with .com! I bookmarked the url on my phone using a bookmarking app service and then opened it on my laptop and it seems to have changed the .app to .com and I didnt notice 😞 
Sorry again for the false alarm.

**Comment by ryohey** [comment]
@maks No prob! Thank you for reporting!

**Comment by ryohey** [comment]
woaaaa it is my mistake
I wrote alternate link tag with `.com` 😂 

fixed  in #199
