### ISSUE TITLE
Shift + arrows don't work

### ISSUE THREAD

**Issue by Softy107** [ryohey/signal#202]
**Describe the bug**
The shift + arrow down/up key binds for higher/lower octave doesn't work 

**To Reproduce**
1. Go to signal.vercel.app
2. place some notes with an octave above or bellow
3. press Shift + [Arrow down/up]

**Expected behavior**
The notes move to the lower/higher octave

**Screenshots**
I don't think I can screenshot this...

**Desktop (please complete the following information):**
 - OS: Windows 10 education
 - Browser : MS Edge
 - Version : Version 103.0.1264.71 (Official build) (64-bit) (browser ver)

**Smartphone (please complete the following information):**

**Additional context**
this does work when pressing the right mouse button and selecting it manually, but I'm used to key bindings.

**Comment by ryohey** [comment]
Thanks! Fixed in #203
