### ISSUE TITLE
Track scrolling doesn't work?

### ISSUE THREAD

**Issue by Softy107** [ryohey/signal#213]
**Describe the bug**
I can't seem to scroll between tracks for some reason.

**To Reproduce**
1. Go to signal.vercell.app
2. load a file with over 12 tracks
3. try to scroll down on the tracks

**Expected behavior**
The tracks should scroll down, revelaing more tracks

**Screenshots**

![Screenshot (254)](https://user-images.githubusercontent.com/103595729/187048864-0bfdacf7-49cc-4b26-bf0d-5b186392eb79.png)
(You can't see it but I am trying to scroll in the screenshot)

**Desktop (please complete the following information):**
  - OS: Windows 10 education
  - Browser : MS Edge
  - Version : 104.0.1293.70 (Official build) (64-bit) (browser ver)

**Smartphone (please complete the following information):**

**Additional context**
In case it only works on certain files, here is the file I was using : https://drive.google.com/file/d/1WGQxfNM_qrOqkJeYlSBVjOEWh5GxH9kg/view?usp=sharing

(Original song is from here, this is a MIDI transcription(?) : https://www.youtube.com/watch?v=31BL-bZyBoU )

**Comment by ryohey** [comment]
@Softy107 Thank you for reporting! I will fix it soon
