### ISSUE TITLE
Right click to delete?

### ISSUE THREAD

**Issue by xcoderreal** [ryohey/signal#23]
Now that we can drag to change duration and pitch, can we add a feature which is right click a note to delete it?

After playing with it for a couple minutes, it looks like the existing alternative to delete a note is to drag it out of the window?

**Comment by ryohey** [comment]
@xcoderreal Hi thank you for your trying my app! You can use selection tool, then right-click to delete notes in selection. Would that work for you?

![image](https://user-images.githubusercontent.com/5355966/94355911-651db300-00c3-11eb-8dc2-23246a6cdeb0.png)
![image](https://user-images.githubusercontent.com/5355966/94355914-6b139400-00c3-11eb-93aa-288eeae1468b.png)

**Comment by xcoderreal** [comment]
Ah got it, just realized there's a selection icon (I didn't try hard enough).

I think my feature request might still be worth investigating though, because from the editor's perspective if there would be a gesture which is like:
1.  Right click, then hold
2.  Move cursor
3.  Any mouseover-ed notes will be deleted
4.  (Release right click)

Software like FL Studio has a gesture like this, and it makes editing very easy (deleting notes is a very common action).

That being said, obviously this is just a suggestion! (My intuition is that it _might_ not be as hard to implement something like this; thought I could be wrong.)

**Comment by ryohey** [comment]
Now we can delete a note by double click. 
But the feature you suggested is very reasonable! I will try it. Thanks.

**Comment by ryohey** [comment]
@xcoderreal Added support for this feature! #32
