### ISSUE TITLE
Adding audio length setting to help exported sound keep sustain and release sound.

### ISSUE THREAD

**Issue by DeqingSun** [ryohey/signal#234]
When the tool export the MIDI as audio file, the sustain and release sound got clipped. It will be helpful to let the user define the length they want to export.

**Comment by ryohey** [comment]
Thank you for supporting us! The endOfTrack, which determines the length of the song, is now automatically calculated, but we will consider the ability to allow users to adjust it manually.

**Comment by DeqingSun** [comment]
@ryohey Thanks for the reply. I thought about it again. It may not be necessary to adjust manually. Just improve the automatically calculation and end the sound file when the rendered sound get fully released, then the problem will be solved with no change to UI.
