### ISSUE TITLE
Language defaults to Japanese

### ISSUE THREAD

**Issue by Dogo6647** [ryohey/signal#241]
**Description:**
The title says it all.

**Steps to reproduce the behavior:**
Open the webapp. That's it.

**Expected behavior:**
The default language should be English, as that's what most people are familiarized with.

**Desktop:**
 - OS: openSUSE Tumbleweed x86_64
 - Browser: Brave (official flatpak)
 - Version: 1.46.144 (Chromium 108.0.5359.128)

**Additional context:**
I have device fingerprinting blocked in Brave Shields, I don't know if Signal uses it to detect the device's language.

**Comment by ryohey** [comment]
oops its my mistake
