### ISSUE TITLE
Track Channel Dropdown Code not Rendering

### ISSUE THREAD

**Issue by sean-7777** [ryohey/signal#255]
**Describe the bug**
Some code is not rendering. Probably just some escaped HTML or such.

**To Reproduce**
1. Create new song
2. Right click on a track
3. Select `Property`
4. Select the `Channel` drop down.
5. Option 10 is `10 ($<Localized default="Rhythm Track">rhythm-track</Localized>)`

**Expected behavior**
The `($<Localized default="Rhythm Track">rhythm-track</Localized>)` to not show.

**Screenshots**
![image](https://user-images.githubusercontent.com/67909939/230647623-3cd69626-9e68-430b-89a1-4e300557caad.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 22H2, build v19045.2728
 - Browser: Opera GX LVL 4 v96.0.4693.127 w/ Chromium v110.0.5481.192

**Comment by sean-7777** [comment]
Update: [/src/main/components/TrackList/TrackDialog.tsx@66](https://github.com/ryohey/signal/blob/676721a1866b60199a83fd306c10ef61fd994e3c/src/main/components/TrackList/TrackDialog.tsx#L66) seems to be the culprit.

**Comment by ryohey** [comment]
oops 
I will fix it.
