### ISSUE TITLE
要望色々

### ISSUE THREAD

**Issue by kazooyer** [ryohey/signal#26]
* 取り消し（Undo）がほしい（Ctrl+z的な）
* ノート置くモードと選択モードをなんかもっと簡単に切り替えたい
* ノート置いたり移動させたりしたときだけじゃなくてクリックしたときにも音出してほしい
* ノート選択した後、DELでノート消したい（Backspaceはできた）
* ダブルクリックでノート消したい
* オニオンスキン的なやつほしい
* 矢印キーの上下でノートの音程移動、左右で選択ノードの移動、Shift+左右で時間移動などしたい
* 複数ノート選択してからノートの長さ変えたら選択中ノート一括で変わってほしい

**Comment by ryohey** [comment]
- [ ] 取り消し（Undo）がほしい（Ctrl+z的な）
- [x] ノート置くモードと選択モードをなんかもっと簡単に切り替えたい
  - 1, 2キーで切り替えできます
- [ ] ノート置いたり移動させたりしたときだけじゃなくてクリックしたときにも音出してほしい
- [x] ノート選択した後、DELでノート消したい（Backspaceはできた）
  - 対応しました 4798495
- [ ] ダブルクリックでノート消したい
- [ ] オニオンスキン的なやつほしい
- [ ] 矢印キーの上下でノートの音程移動、左右で選択ノードの移動、Shift+左右で時間移動などしたい
- [ ] 複数ノート選択してからノートの長さ変えたら選択中ノート一括で変わってほしい

ヘルプ追加！

![image](https://user-images.githubusercontent.com/5355966/94369588-962ecf80-0125-11eb-969e-2bb4a63264ed.png)

**Comment by ryohey** [comment]
close #38
