### ISSUE TITLE
SetTempo event ticks are not imported correctly

### ISSUE THREAD

**Issue by cihadturhan** [ryohey/signal#266]
**Describe the bug**
For some files, SetTempo events has incorrect ticks.

**To Reproduce**
1. Download the following MIDI: 
[River_Flows_in_You (2).mid.zip](https://github.com/ryohey/signal/files/11507358/River_Flows_in_You.2.mid.zip)
2. Import into signal.vercel.app
4. Go to `Tempo` tab
5. See all the SetTempo events are between `1:01-2:02` bars:
6. 
![image](https://github.com/ryohey/signal/assets/3739536/42848318-940a-407b-a53b-bdfbf9c18db4)

**Expected behavior**
1. Import into another app (I use studio one) and check setTempo events:
![image](https://github.com/ryohey/signal/assets/3739536/ae4faaf7-4394-426d-a4e1-12fc7653a29d)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari]: Chrome

Might be related to #263

**Comment by ryohey** [comment]
This issue has been fixed in #267. Thanks for the very detailed report!
