### ISSUE TITLE
バグっぽい挙動

### ISSUE THREAD

**Issue by kazooyer** [ryohey/signal#27]
* 右クリするとブラウザの右クリメニューも出る
* 曲作ってる途中からBPMの変更できなくなった（下の入力欄で変更しても変わらない）
* いろんなmidiファイルを読み込むと前のmidiのごみらしきものが残る（表示上だけ）

**Comment by ryohey** [comment]
- [x] 右クリするとブラウザの右クリメニューも出る dbac084
- [x] 曲作ってる途中からBPMの変更できなくなった 6ddf987 
- [ ] 前のmidiのごみらしきものが残る

**Comment by ryohey** [comment]
選択ツールで編集、元に戻すを行うと Stage 上に store に無いノートが残ることがあった。
c588ba0 でおそらく直った
