### ISSUE TITLE
Time signature changes do sometimes not work/produce unexpected behaviour

### ISSUE THREAD

**Issue by b1a0** [ryohey/signal#276]
First of all, thank you for this great app! 

I noticed a small bug, that for me only appears when using the app in Firefox (my version is 116.0.2), but works in Chrome. When I add time signature changes within a song, sometimes the time signature does not update correctly (while the symbol is still being displayed in the time signature line) and sometimes a time signature change is not recognized at all (no change, and also not displayed in the time signature line). 

**Steps to reproduce the behavior**
1. Start with a 4/4 time signature track starting at bar 0
2. Insert 3/4 time signature at bar 1 - > this works, displays the 3/4 signature above bar 1 and updates the signature
3. Insert time signature 4/4 at bar 2 -> this displays 4/4 at bar 2, but the bar still stays 3/4
4. Insert time signature 3/4 at bar 3 -> does not insert time signature symbol and does not update time signature

**Expected behavior**
I would have expected the time signature to be changed. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 116.0.2
![20230812_timesignature](https://github.com/ryohey/signal/assets/54393590/946ec26a-f48c-4c33-9a47-4954a2c6dd92)

**Comment by b1a0** [comment]
I found an additional problem, this time also in Chrome. When we have multiple time signature changes and want to change one of the earlier ones, the time signature can be inserted but it is not updated:

**Steps to reproduce the behavior**
1. Start with a regular track with 4/4 time signature at bar 0
2. Insert 3/4 time signature at bar 1
3. Remove time signature at bar 0
4. Add 5/4 time signature at bar 0 -> the symbol is inserted but the time signature of bar 0 is not updated

**Expected behavior**
I would have expected the time signature to be changed.

**Desktop:**

  OS: Ubuntu
  Browser: Chromium
  Version: 116.0.5845.110

**Comment by ryohey** [comment]
Fixed in https://github.com/ryohey/signal/issues/276

**Comment by ryohey** [comment]
@b1a0 Thank you for the detailed report!
