### ISSUE TITLE
Firebase Error when running the web app.

### ISSUE THREAD

**Issue by victorshop** [ryohey/signal#295]
**Describe the bug**
I was able to `npm run` the web app, but when click the "launch" on the home page, i saw the webpage has this error: 

FirebaseError
Firebase: Error (auth/invalid-api-key).
Call Stack
 createErrorInternal
  browserMain-ae7e0651145cb32a8147.js:4070:40
 _assert
  browserMain-ae7e0651145cb32a8147.js:4074:15
 Component.instanceFactory
  browserMain-ae7e0651145cb32a8147.js:13961:9
 Provider.getOrInitializeService
  browserMain-ae7e0651145cb32a8147.js:179220:39
 Provider.initialize
  browserMain-ae7e0651145cb32a8147.js:179164:31
 initializeAuth
  browserMain-ae7e0651145cb32a8147.js:6881:27
 getAuth
  browserMain-ae7e0651145cb32a8147.js:14051:18
 ./src/firebase/firebase.ts
  browserMain-ae7e0651145cb32a8147.js:67709:68
 options.factory
  browserMain-ae7e0651145cb32a8147.js:194159:31
 __webpack_require__
  browserMain-ae7e0651145cb32a8147.js:193534:33

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser chrome, safari

**Comment by victorshop** [comment]
![Screenshot 2023-12-28 at 00 03 52](https://github.com/ryohey/signal/assets/127332346/a0abbacf-6899-4180-804b-5fb3fc06d2e0)

**Comment by ryohey** [comment]
@victorshop Hi, I recently received a warning email from Google, so I stopped including the API key in the repository and revoke the key. Please register your own Firebase project and write the API key and other information in the `.env` file. I just committed a `.env.example` file, so please copy this file to create your `.env` file.
