### ISSUE TITLE
Note Velocity does not have a limit to it's value

### ISSUE THREAD

**Issue by Softy107** [ryohey/signal#301]
**Describe the bug**
When using the Event List to edit the velocity of notes, the max value is not 127, and it can reach way further.
The note color also distorts.
The value can also go into the negative part

**To Reproduce**
1. Place A Not
2. Open Event List
3. Change note velocity to anything past 127

**Expected behavior**
The note value automaticly edits it self

**Screenshots**
![image](https://github.com/ryohey/signal/assets/103595729/3a132395-401a-425f-afb3-06046d9e9c40)

**Desktop (please complete the following information):**
 - OS: Windows 10 Education
 - Browser MS Edge
 - Version Verze 120.0.2210.121 (Oficiální build) (64bitová verze)

**Additional context**
Notes do not appear in the MIDI it self for some reason

**Comment by ryohey** [comment]
Thanks for reporting!
Fixed in #310
