### ISSUE TITLE
Locks up attempting to edit .mid channels exported from MuseScore

### ISSUE THREAD

**Issue by yoitsOJ** [ryohey/signal#320]
**Explanation:**
For context, I'm in the middle of a project rewriting a marching band piece to run it through Midis2Jam2. When I export the .mid through MuseScore, the instruments are all sorts of mismatched, so I run it through signal so I can reassign and adjust the channels as needed.
However, after my latest update to the project, I can't change anything in the file with signal. When I click on one instrument, it freezes with a greyish (my chrome profile is grey so I'm guessing it's just that) screen for a second or two, then allows me to edit the channel, but then when I go to the next instrument, it fully locks up with a solid white screen, and I'm forced to reload the page and start over, which then the same thing will happen.

**To Reproduce:**
1. Grab the mid [here](https://drive.google.com/file/d/1tsluBF1Do1gFXiD4NfMZdzMYDTa8yMRs/view?usp=sharing)
2. Open it
3. Double click on a channel to edit it's instrument.
4. If it doesn't lock up yet, open another channel and try to edit it's instrument.
5. If it doesn't lock up by the second or third change then it might just be my dogshit MacBook

**System and Program Info:**
 - 2017 MacBook Pro
 - MacOS Ventura 13.6.1
 - Google Chrome 121.0.6167.184
 - Latest version as of 2/19/2024 20:30 EST (8:30pm EST)

**Comment by ryohey** [comment]
Hi, I could not reproduce it on my device. Does it happen in different browsers?

**Comment by yoitsOJ** [comment]
Hello, so I’ve actually fixed it myself. It turns out my MacBook was just
so shitty that Signal would crash opening big midi files. It works fine on
my pc and other laptop.

**Comment by ryohey** [comment]
Thanks for confirming it!
