### ISSUE TITLE
Why not PWA? 

### ISSUE THREAD

**Issue by louiesun** [ryohey/signal#326]
**Is your feature request related to a problem? Please describe.**
I want to use it offline. 

**Describe the solution you'd like**
As I known, the project if completely Javascript, so we it produces an static website. 
To make it offlineable, why not simply use PWA to storge the js files(alse html&css) offline in the browser. 

**Describe alternatives you've considered**

**Additional context**
Many tools project use PWA so they are available offline such us [stackedit](https://github.com/benweet/stackedit)

[ReactPWA](https://create-react-app.dev/docs/making-a-progressive-web-app/)

**Comment by ryohey** [comment]
Signal is compatible with PWA. Offline functionality is not implemented. Please consider joining our supporter to help develop free apps.  https://github.com/sponsors/ryohey

Close this issue due to duplication #209
