### ISSUE TITLE
Cannot load some midi files

### ISSUE THREAD

**Issue by hipe-0** [ryohey/signal#327]
**Describe the bug**

i tried with 2 files and it results with a blank screen. and nothing. 

**To Reproduce**
go to "importer un fichier"
choose my file
blank screen

**Expected behavior**
it should have loaded the midi file

**Screenshots**
blank screen
![2024-03-03 18_35_41-NVIDIA GeForce Overlay](https://github.com/ryohey/signal/assets/133164832/f20f6e32-c296-401b-bd1f-7a0bc8f34e2c)

**Desktop (please complete the following information):**
win 11

**Additional context**
the file:
[Harry Potter Theme.zip](https://github.com/ryohey/signal/files/14473943/Harry.Potter.Theme.zip)

please make it work it's a good idea to have a functionnal midi editor online today in 2023

**Comment by ryohey** [comment]
That MIDI file can be opened normally. Select the Open menu from the File button.
<img width="317" alt="image" src="https://github.com/ryohey/signal/assets/5355966/cf59cfae-e308-4d5a-9f8c-80ccdfb4f88b">
