### ISSUE TITLE
Add Undo functionality

### ISSUE THREAD

**Issue by hipe-0** [ryohey/signal#328]
**Is your feature request related to a problem? Please describe.**
I'm missing the undo button. the software is unworkable if no undo button (and no answer to CTRL+Z)

**Describe the solution you'd like**
the "undo" button should remember the previous states and each press on undo should go back to a previous version of the edited notes that's remembered

**Describe alternatives you've considered**
please no alternative. a simple straight forward undo button with regular undo icon and key press "CTRL + Z".

**Additional context**

If you're serious about this software. please add this feature . seriously. thanks !

**Comment by ryohey** [comment]
There is an undo function, try Ctrl+Z or Cmd+Z.
