### ISSUE TITLE
Midi recording not working

### ISSUE THREAD

**Issue by r-ahurley** [ryohey/signal#384]
**Describe the bug**

cannot record using a Donner N25 midi keyboard. Donner is working in other applications. I hit option R on my Mac, recording button activates on the screen as if to receive Midi signals but when I play my Donner piano keyboard nothing appears on screen and I have nothing to export. My Donner is working in another midi application I am building myself. The Donner worked on Signal/Vercel one week ago when I recorded 30 test files. Nt working now.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ryohey** [comment]
Make sure the device is listed in the Inputs section of the MIDI setup and checkmark it. <img width="518" alt="image" src="https://github.com/user-attachments/assets/e5054d9a-aea3-43bb-a7a2-e7e46ac17220">
