### ISSUE TITLE
Pressing "Log In" makes the screen go white

### ISSUE THREAD

**Issue by telsm** [ryohey/signal#395]
I can't log into my account anymore. Whenever I click the Log In button on the top, everything goes white and I lose any sight of interactive GUI.

Look at this shit.

<img width="1231" alt="Screenshot 2024-08-18 at 3 54 18 PM" src="https://github.com/user-attachments/assets/1af26894-5b80-4041-b3a1-44c800eb6583">

Does anybody else have this issue? If they do, then I'd gladly accept this issue being resolved completely.

**Comment by ryohey** [comment]
omg i'll fix it

**Comment by ryohey** [comment]
fixed it now thank you for reporting
