### ISSUE TITLE
Grid Lines Turn Into Giant Triangles on Firefox

### ISSUE THREAD

**Issue by Thysbelon** [ryohey/signal#418]
**Describe the bug**
When [Signal](https://signal.vercel.app/edit) is opened in Firefox, grid lines and notes will appear as giant triangles instead of vertical lines and rectangles.

**To Reproduce**
1. [Launch Signal midi editor](https://signal.vercel.app/edit) in Firefox version 132
2. Observe the giant grey triangles on screen
3. Observe that notes will be giant blue triangles

**Expected behavior**
Grid lines should be vertical lines and notes should be small rectangles.

**Screenshots**
***Desktop***
![Screenshot from 2024-10-30 21-16-56](https://github.com/user-attachments/assets/398fe855-d5f9-488f-9faa-cc54e9a9e3bf)
***Smartphone***
![Screenshot_20241030-212135](https://github.com/user-attachments/assets/19f4d8c2-0c26-48d2-a41f-61b888206c0d)

**Desktop:**
 - OS: Ubuntu 24.04.1 LTS
 - Browser: Mozilla Firefox Snap for Ubuntu 132.0 (64-bit)

**Smartphone:**
 - Device: Google Pixel 3a
 - OS: Android 12
 - Browser: Firefox 132

**Additional context**
This issue did not occur on previous versions of firefox. I believe the last time I used Signal was October 1st, and I did not experience this issue then. I may have been using version 130.0.1 at that time.

**Comment by kabss90** [comment]
how did it sound like
