### ISSUE TITLE
Graphics are completely broken on 'signal.vercel.app'.

### ISSUE THREAD

**Issue by damienwolf07** [ryohey/signal#420]
**Describe the bug**
It appears the graphic canvas is having a mental breakdown XD.
Jokes aside, All graphics are broken and are completely unusable, However, Loaded MIDI files still play fine (no problem there).

**To Reproduce**
1. Go to ['signal.vercel.app'](https://signal.vercel.app/edit).

**Expected behavior**
Expected behavior is to have readable notes and be editable, Not a abstract mess!

**Screenshots**
![image](https://github.com/user-attachments/assets/8d3ba814-e20f-4c28-abd3-5f46738d6ae7)
![image](https://github.com/user-attachments/assets/a4fd3b3b-1735-4e3d-82a6-24c1548ebbd0)
![image](https://github.com/user-attachments/assets/ac4edf68-eb4c-4304-8382-9817dcf62752)
![image](https://github.com/user-attachments/assets/03de7544-4c7d-4dd9-b515-8a33d0d37914)
![image](https://github.com/user-attachments/assets/b26cac8b-37d9-41da-ad95-3ea1a7111b0a)

**Desktop (please complete the following information):**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0

**Smartphone (please complete the following information):**
N/A.

**Additional context**
N/A.

**Comment by robertnhart** [comment]
This appears to be the same thing reported in #418 Grid Lines Turn Into Giant Triangles on Firefox

**Comment by ryohey** [comment]
ok it happened on 132.0 but not on 130.0.1. It is possible it is a bug in the browser, but I will look into it.
