### ISSUE TITLE
Realistic sounds

### ISSUE THREAD

**Issue by surikov** [ryohey/signal#48]
**Is your feature request related to a problem? Please describe.**
You need more realistic sounds

**Describe the solution you'd like**
use
https://github.com/surikov/webaudiofont

**Comment by ryohey** [comment]
It sounds wonderful!
After some trial implementations, it was easy to simply integrate it into signal and produce sounds, but it seemed that a lot of code would need to be written to handle pitch bend and rhythm tracks, so I decided not to integrate webaudiofont for the time being. However, I will continue to consider the use of SoundFont precompiled to json and other great features such as asynchronous loading per tone.
Thanks!

**Comment by surikov** [comment]
Pitch bend implemented already, see examples
