### ISSUE TITLE
Notes Not Working

### ISSUE THREAD

**Issue by Finman2000** [ryohey/signal#60]
The bug(s) occurring is seemingly random and has multiple effects
 - Notes not being able to extend properly
 - Notes playing at the wrong time, not matching what is being shown on screen
 - Notes not playing at all despite showing up on-screen/playing when nothing shows up on-screen

**Steps to reproduce the behavior:**
1. Go to 'signal.vercel.app/edit'
2. Start creating
3. Using the selection tool to copy + paste identical patterns seems to create problems?

I'm not sure exactly what is causing the problem but, for me, it has happened every time I've tried to create a song, eventually.

The expected behavior is obviously that notes are created, played, and copied normally
The bugs mostly become clear with a video: https://youtu.be/r63KQql1EWs

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome (incognito)
 - Pretty sure it's the latest version as of posting (4/19/2021)

**Comment by ryohey** [comment]
Thank you for reporting! I will investigate more. That video is very helpful.
